# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: swift
xcode_workspace: ./Example/BouncyCastle-ObjC.xcworkspace
xcode_scheme: BouncyCastle-ObjC-Example
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
# cache: cocoapods
jdk: openjdk11
before_install:
  - export JAVA_HOME=$HOME/openjdk11
  - $TRAVIS_BUILD_DIR/install-jdk.sh --url 'https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_osx-x64_bin.tar.gz' --target $JAVA_HOME
  - gem install cocoapods
  - cd ./Example/
install:
  - pod install --verbose
script:
  - set -o pipefail
  # check J2ObjC works
  - cat ../BouncyCastle-ObjC/Classes/Base64.h
  - xcodebuild -workspace BouncyCastle-ObjC.xcworkspace -scheme BouncyCastle-ObjC-Example -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iPhone X"