# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10.2
language: swift
xcode_workspace: ./Example/BouncyCastle-ObjC.xcworkspace
xcode_scheme: BouncyCastle-ObjC-Example
xcode_destination: platform=iOS Simulator,OS=12.2,name=iPhone X
jdk:
  - oraclejdk8
# cache: cocoapods
before_install:
  - gem install cocoapods
  - cd ./Example/
script:
  - set -o pipefail
  - java -version
  - pod install --verbose
  # check J2ObjC works
  - cat ../BouncyCastle-ObjC/Classes/Base64.h
  - xcodebuild -workspace BouncyCastle-ObjC.xcworkspace -scheme BouncyCastle-ObjC-Example -sdk iphonesimulator -destination "platform=iOS Simulator,OS=12.2,name=iPhone X" | xcpretty -c